export default {
    SET_IMAGE_LIST: "SET_IMAGE_LIST",
    SET_INDEX: "SET_INDEX",
    SET_DESIGNS: "SET_DESIGNS",
    SET_PALETTE: "SET_PALETTE",
};
export const SET_TYPES = {
    IMAGE_LIST: "SET_IMAGE_LIST",
    INDEX: "SET_INDEX",
    DESIGNS: "SET_DESIGNS",
    PALETTE: "SET_PALETTE",
};
