export default {
    SET: "SET",
    SET_IMAGE: "SET_IMAGE",
    SET_TEXT: "SET_TEXT",
    SET_COLORS: "SET_COLORS",
    SET_TEXT_STYLES: "SET_TEXT_STYLES",
    SET_SIZE: "SET_SIZE",
};

export const SET_TYPES = {
    IMAGE: "SET_IMAGE",
    TEXT: "SET_TEXT",
    COLORS: "SET_COLORS",
    TEXT_STYLES: "SET_TEXT_STYLES",
    SIZE: "SET_SIZE",
};
